### ISSUE TITLE
GSTS still not working

### ISSUE THREAD

**Issue by lchugh-uptycs** [ruimarinho/gsts#101]
GSTS --version
5.0.1

moved credentials files from .aws folder to ~/Liberary/cache/gsts folder as well

Error: Got status code "400" while requesting "https://accounts.google.com/o/saml2/initsso?idpid=XXX,XXX&spid=ABC,ABC&forceauthn=false"

somehow my idpid and spid is getting populated twice in the URL (xxx,xxx :: abc,abc)

**Comment by ruimarinho** [comment]
@lchugh-uptycs you should remove `~/.aws/credentials` altogether and let gsts do its things. When it comes to `idpid` and `spid`, I have no idea how they are getting populated with multiple values. The only explanation that I have is that they're being passed exactly as shown.
