### ISSUE TITLE
allow setting puppeteer executablePath

### ISSUE THREAD

**Issue by lizthegrey** [ruimarinho/gsts#21]
For my new aarch machine, puppeteer ships with the x86_64 binary still, and that won't be runnable; thus, I need to [override executablePath](https://github.com/puppeteer/puppeteer/issues/550#issuecomment-551991273)

Is it possible to support a command line flag for specifying a custom chromium to run instead of puppeteer's default? e.g. `executablePath: '/usr/bin/chromium-browser'`

**Comment by ruimarinho** [comment]
Yep, sounds good to me. Will try to add that in.

**Comment by ruimarinho** [comment]
Added in https://github.com/ruimarinho/gsts/commit/f92cda7d4e2fa43c0fea3446ff1c62c7401bb5c3. Let me know if it works for you!

**Comment by lizthegrey** [comment]
Thanks! Will try!

**Comment by lizthegrey** [comment]
It works! Also had to jury-rig `ln -s ~/snap/chromium/current/.local/share/gsts ~/.local/share/` but after that it was fine (snap sandboxing means that it can't write to ~/.local in my own homedir).

**Comment by ruimarinho** [comment]
Nice! Would be great to check if it is swallowing write errors due to lack of permissions and attempt to offer an alternative. Does snap sandboxing offer writable destinations by default?

**Comment by lizthegrey** [comment]
It does, because $HOME is set to /home/$USER/snap/chromium/current/ instead of to /home/$USER by the wrapper script.

**Comment by ruimarinho** [comment]
@lizthegrey which version of Ubuntu are you using? I setup a VM with 18.04, installed Chromium via `snap install chromium`, set the executable to `/snap/chromium/current/usr/lib/chromium-browser/chrome`, and it worked without problems. I can also see `/home/$USER/.local/share/gsts` was created successfully.

There are a few fixes I'm about to publish related to a function that interacts with the filesystem, but your error is happening before the code hits this point.

Could you please log the output of https://github.com/ruimarinho/gsts/blob/master/index.js#L19? Here it shows:

```
{ data: '/home/$USER/.local/share/gsts',
  config: '/home/$USER/.config/gsts',
  cache: '/home/$USER/.cache/gsts',
  log: '/home/$USER/.local/state/gsts',
  temp: '/tmp/$USER/gsts' }
```
