### ISSUE TITLE
Google is detecting puppeteer :(

### ISSUE THREAD

**Issue by lizthegrey** [ruimarinho/gsts#23]
both with --experimental-u2f-support and not, puppeteer is being blocked.

**Comment by ruimarinho** [comment]
Can you please update to v2.3.0? That should fix it.

**Comment by lizthegrey** [comment]
Works, thanks! Sorry about the scare.

**Comment by ruimarinho** [comment]
My original goal was to use headful authentication for the purpose of avoiding this sort of workarounds and hacks, but seems like Google doesn't like that approach even if it's controlled by a human.

Unfortunately it doesn't seem to be possible to use the local Chromium (manually launched, not via puppeteer) and then read that data via puppeteer (https://github.com/puppeteer/puppeteer/issues/5818). We'll see..
