### ISSUE TITLE
Getting gsts: command not found

### ISSUE THREAD

**Issue by akifkamal** [ruimarinho/gsts#24]
I successfully installed gsts using yarn but getting command not found when trying to use gsts.

**Comment by akifkamal** [comment]
Ah...It seems links are broken when I installed it in ubuntu. Accessing it via ~/.yarn/bin/gsts works

**Comment by ruimarinho** [comment]
@akifkamal would you suggest adding something to the README to help other users?

**Comment by akifkamal** [comment]
@ruimarinho  I can create the PR if it is ok with you.

**Comment by ruimarinho** [comment]
Absolutely!
