### ISSUE TITLE
Tmux captures input for Headful Browser

### ISSUE THREAD

**Issue by dtardoin** [ruimarinho/gsts#25]
When launching the headful browser from a tmux session, tmux captures keyboard input so you can't type into any fields in the browser window, makes it hard to enter a password. (I was able to successfully submit the password form when running the exact same command outside of tmux, so I figure that's to blame)

Not sure if there's anything to be tweaked within gsts to fix this or not.

**Comment by ruimarinho** [comment]
Just tried in tmux on macOS without any issue.. 🧐 any specific setting I should try to replicate?

**Comment by ruimarinho** [comment]
@dtardoin let me know if you find a way to replicate this! Closing for now.
