### ISSUE TITLE
Mac Install (Brew?)

### ISSUE THREAD

**Issue by Rucknar** [ruimarinho/gsts#27]
I'm keen to make more use of this tool in my team (users of aws-google-auth just now).
The install process however requires npm or yarn which isn't part of the majority of our setups.

Is there a possibility we could make use of something like brew to make installing this easier or would you still need the node env installing on the mac?

**Comment by ruimarinho** [comment]
Indeed, it's definitely not ideal. I'm a user of brew myself and I can create a tap to make the process a lit bit easier.

You would still need the node dependency, but it would be automatically installed by brew. There are some projects out there which we could consider like https://github.com/nexe/nexe.

**Comment by Rucknar** [comment]
Can't say i've much experience with nexe perfectly but Brew would suit out needs just fine. Happy to test out a tap with out users if that helps?

**Comment by ruimarinho** [comment]
Hey @Rucknar! I'm working with some colleagues on getting this into the official homebrew package. The formula is pretty much ready - we were just trying to find a better way of testing the existence of the binary without just running `--help`. Should be up shortly for review.

**Comment by Crevil** [comment]
@ruimarinho any additional progress on the brew tap? And further, anything I can do to help get this completed?

**Comment by ruimarinho** [comment]
@Crevil @Rucknar I've just released a tap for gsts! Thanks for your patience ;) https://github.com/ruimarinho/gsts/commit/1262c9af23618b8d2ddf638c51a7f998b28875d7

If you're so kind and you'd like to remove the additional tap install step, you may submit the exact same `gsts.rb` to the upstream repository under https://github.com/Homebrew/homebrew-core.

**Comment by Crevil** [comment]
Thank you 🙌 This is great news. 🙏
