### ISSUE TITLE
Security key not detected

### ISSUE THREAD

**Issue by lizthegrey** [ruimarinho/gsts#3]
For some reason, when chromium is executed by puppeteer, my security key's light never comes on, and tapping it has no effect. I had to use backup codes to log in with gsts.

This is on Ubuntu Linux, gsts version 2.1.0

**Comment by ruimarinho** [comment]
Hi @lizthegrey! Unfortunately I am experiencing the same issue on macOS. I am pretty sure it was working before..

I have tried to direct `gsts` to the traditional login page (`https://accounts.google.com`) and it works fine there, so it must be some kind of legacy check of the U2F script that is still in use by that particular page.

I'll see if someone over at the puppeteer project can shed some light on this. Thanks for the report!

**Comment by Zlender** [comment]
I just tried gsts for the first time yesterday and couldn't figure out how to get security key to light up during MFA step with Google. If I open webauthn demo site in same browser in new tab I can use it just fine https://demo.yubico.com/webauthn-technical/registration . 

Maybe completely unrelated but if I just go to login to gmail.com with my corp account I get this error from google
```
Couldn't sign you in
This browser or app may not be secure. Learn more
Try using a different browser. If you’re already using a supported browser, you can refresh your screen and try again to sign in.
```

Learn more leads to https://support.google.com/accounts/answer/7675428?hl=en

**Comment by lizthegrey** [comment]
https://accounts.google.com/signin/challenge/sk/3 [...] fails

https://accounts.google.com/signin/v2/challenge/sk/webauthn [...] succeeds

I'll ask the Chrome Googler sitting next to me to help me out ;)

**Comment by ruimarinho** [comment]
What a fun trip this was! Experimental supported now enabled on https://github.com/ruimarinho/gsts/tree/v2.2.0.

Added a section to the README with a 'postmortem' of this bug (https://github.com/ruimarinho/gsts/tree/v2.2.0#security-keys--webauthn--u2f).

Please give it a try with `--enable-experimental-u2f-support` (just to play a bit with Chrome switches). If everything goes well it might be enabled by default in the future.

I'm going to close this issue as I'm confident it will work 😅
