### ISSUE TITLE
Chromium not launching on macOS Big Sur 11.0.1 / iTerm 2

### ISSUE THREAD

**Issue by christopher-wong** [ruimarinho/gsts#36]
After attempting to login using iTerm2 `gsts` gets stuck `Logging in` and Chromium never launches to continue the login flow.

**Comment by bitflingr** [comment]
I too have a similar problem, however I managed to see chromium launch if i pass a blank `--idp-id`.  It launches the browser and throws an error as expected so it must be something before launching the browser.  I have not had any luck getting anything else meaningful from `--verbose` or any logs from the command.

**Comment by bitflingr** [comment]
@christopher-wong 
This seems to be maybe more of a Big Sur -> iTerm2 update.  I was able to successfully login just using the default Terminal in MacOS.  Once done i was then able to refresh my login in iTerm2 just fine.

**Comment by christopher-wong** [comment]
@bitflingr is absolutely right - works fine in Terminal.app but not in iTerm 2.

**Comment by ruimarinho** [comment]
Thanks for the reports! I haven't tested Big Sur yet, but I wonder if it's some Accessibility or Automation privacy security setting blocking the UI to be launched? 

It could also be `env-paths` or `require('os').homedir()`.

**Comment by ruimarinho** [comment]
Added a [note on the README](https://github.com/ruimarinho/gsts#big-sur-compatibility). Please take a look and let me know if it solved the issue for you.

**Comment by assapir** [comment]
Confirming it resolve the issue, thanks!

**Comment by ShayMe21** [comment]
I can confirm as well that default MacOS terminal works fine.
But on iTerm2 it doesn't launch the Chromium browser.

Big Sur v11.1 (20C69)
iTerm 2 Build 3.4.3

**Comment by ruimarinho** [comment]
@ShayMe21 has the workaround listed in the README help?

**Comment by ShayMe21** [comment]
> @ShayMe21 has the workaround listed in the README help?

Yes it did. sorry forgot to update my comment. Manually giving iterm Bluetooth permission worked without any issues.
