### ISSUE TITLE
Potential upcoming breakage - Google blocking login automation?

### ISSUE THREAD

**Issue by wryun** [ruimarinho/gsts#37]
I've just noticed: https://developers.googleblog.com/2020/08/guidance-for-our-effort-to-block-less-secure-browser-and-apps.html

I added the following to gsts, as suggested for testing purposes:

```
  await page.setExtraHTTPHeaders({
    'Google-Accounts-Check-OAuth-Login': 'true'
  });
```

Seemed to cause things to fall over, but I may have made a mistake.

Not sure if this is an issue, but since I didn't see an existing one I thought I'd create it (even if it only needs to be closed).

**Comment by ruimarinho** [comment]
Oh, wow! Thanks for the heads up. Have you faced blocks already (without the header)?

**Comment by wryun** [comment]
Nope, it's been fine so far. Thanks very much for making this and making everything just work. I haven't had to think about how we auth to AWS for a while, which is a pleasant change (aws-google-auth fell over repeatedly, and I though 'well, if we're using a _real_ browser surely this will be fine...').

**Comment by ruimarinho** [comment]
Glad you're enjoying this little tool! My goal was precisely that - to simply use the browser like a real human. In fact, my original idea was to simply point your existing Chrome profile user data dir and cookies would be re-used. Unfortunately, it seems headless mode was made made incompatible with existing profiles on purpose to avoid automation of this kind. It's a matter of time before Google blocks legitimate uses like this one, but let's enjoy it while it lasts! I'll do my best to keep it alive.
