### ISSUE TITLE
Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by michaelconnor00** [ruimarinho/gsts#38]
I am trying to install this tool using the `credential_process`. I have all the values as per the docs. When I run a test command such as `aws sts get-caller-identity` or `aws ec2 describe-instances `, I get the following output `Expecting value: line 1 column 1 (char 0)`. I must be missing something.

I am a Linux user if it helps.

**Comment by ruimarinho** [comment]
Have you tried running in verbose mode to see if the output matches your credentials?

**Comment by michaelconnor00** [comment]
Here is a verbose output.
```
➜ gsts --aws-role-arn arn:aws:iam::<account_id>:role/aws-reserved/sso.amazonaws.com/AdministratorAccess --sp-id <sp_id> --idp-id <idp_id> --verbose
ℹ Attempting to retrieve session expiration credentials
ℹ Request to "https://us-east-1.signin.aws.amazon.com/platform/saml/acs/<some_id>" has been aborted
```

**Comment by ruimarinho** [comment]
@michaelconnor00 it seems like sso.amazonaws.com uses a different flow to authenticate. Can you tell me which requests are made when? I believe that domain must be whitelisted, or gsts will automatically abort the request.

**Comment by michaelconnor00** [comment]
The awscli v2 had the sso support we needed. I don't think I understood what I needed when I created this issue. I will close it. Thanks.

**Comment by ruimarinho** [comment]
@michaelconnor00 are you using AWS SSO with Google Workspace?

**Comment by michaelconnor00** [comment]
Yes.
