### ISSUE TITLE
Remove profile prefix when saving the aws config

### ISSUE THREAD

**Issue by tushar-nallan** [ruimarinho/gsts#43]
I see that the profile is saved as. [profile sts] instead of just [sts].

This causes the following error to be thrown during compilation -

Your profile name includes a 'profile ' prefix. This is considered part of the profile name in the Java SDK, so you will need to include this prefix in your profile name when you reference this profile from your Java code.

If I remove the profile prefix manually, this error is gone. Is this something we can fix here or the issue should go someplace else?

aws issue link: https://github.com/aws/aws-sdk-java/issues/1707

Thanks!

**Comment by ruimarinho** [comment]
Hi @tushar-nallan,

gsts stores just the key, not `profile [key]`. See https://github.com/ruimarinho/gsts/blob/master/credentials-manager.js#L209-L214, so I believe what you're seeing comes from some other software.

Cheers,
