### ISSUE TITLE
Does not respect system default browser

### ISSUE THREAD

**Issue by alper** [ruimarinho/gsts#47]
Is it expected that gsts would pop Chromium instead of my system default Safari?

**Comment by ruimarinho** [comment]
Hi @alper. Short answer, yes. `gsts` uses playwright under-the-hood, which bundles Chromium/WebKit/Firefox. You can use any of these three, but none of them will actually be your installed browser. Recently, playwright added compatibility with stable channels.

From https://playwright.dev/docs/browsers:

> Each version of Playwright needs specific versions of browser binaries to operate. By default Playwright downloads Chromium, WebKit and Firefox browser versions that it supports. With every release, Playwright updates the versions of the browsers it supports, so that the latest Playwright would support the latest browsers at any moment.

> For Google Chrome, Microsoft Edge and other Chromium-based browsers, by default, Playwright uses open source Chromium builds. These builds match the current Chrome Dev Channel at the time of each Playwright release, i.e. it is new with every Playwright update. Since Chromium project is ahead of the branded browsers, when the world is on Google Chrome 89, Playwright already supports Chromium 91 that will hit Google Chrome and Microsoft Edge if a few weeks.

> There is also a way to opt into using Google Chrome's or Microsoft Edge's branded builds for testing. For details on when to opt into stable channels, refer to the Google Chrome & Microsoft Edge section below. section below.

This means pointing to a locally installed version of Google Chrome should actually work a lot better now, but still requires tinkering with some config values (see https://playwright.dev/docs/api/class-browserserver#browserserverwsendpoint).

Give it a shot and let us know if works for you.
