### ISSUE TITLE
Full exit on errors.RoleNotFoundError

### ISSUE THREAD

**Issue by rustymagnet3000** [ruimarinho/gsts#49]
When the following code fires:

```javascript
if (e instanceof errors.RoleNotFoundError) {
  logger.error(`Role ARN "${argv.awsRoleArn}" not found in the list of available roles ${JSON.stringify(e.roles)}`);
  route.abort();
  return;
}
```

`gsts` does not return an error code to the O/S.  It appears to hang on macOS and doesn't return to the command prompt.  

https://github.com/ruimarinho/gsts/blob/bde055fa130ca0e99097c8e0aee0b3c05325920e/index.js#L294

```
▶ gsts --version                                                                   
3.0.6

```

**Comment by ruimarinho** [comment]
@rustymagnet3000 could you give v3.0.7 on npm?

**Comment by rustymagnet3000** [comment]
I can't create a new branch ( before I create a PR ) on your gsts repo.

Could you add me, please?

`ERROR: Permission to ruimarinho/gsts.git denied to rustymagnet3000`
