### ISSUE TITLE
[BUG] Unable to launch browser on OSX 12

### ISSUE THREAD

**Issue by Skarlso** [ruimarinho/gsts#50]
Hello.

Playwright had an update a couple month ago to support OSX 12 here: 
https://github.com/microsoft/playwright/issues/7624

`gsts` needs to update its dependency in order for it to work from 12 onwards. Right now, `gsts` isn't working because it can't launch the browser.

**Comment by ruimarinho** [comment]
I'm testing an update right now but I'm having some inconsistent results where the Chromium window sometimes doesn't close. Have you had this happening to you @Skarlso? I may publish this as v4..

**Comment by Skarlso** [comment]
@ruimarinho Hmm... interesting. Nope, I've been using this consistently for the past week. I didn't notice any issues yet. I'll try and clear my cache and make it open the window more often. :)

**Comment by treykasada** [comment]
I'm currently running @Skarlso's fork to workaround this issue, and so far it's been fine. I haven't yet had Chromium open though, so can't confirm if there are issues with the browser closing, but everything else seems fine. 🙂

**Comment by Skarlso** [comment]
Used this past 6 days clearing cache so it opens every time. I haven't had any problems yet 🤞 .

**Comment by Skarlso** [comment]
Just happened to me. But, to be honest, it happened in what... a timeframe of several days as opposed to not working at all without this update. ¯\\_(ツ)_/¯

**Comment by treykasada** [comment]
Agreed; I don't think the window not closing is problematic enough to block shipping this fix. I'll take "working with occasional UX problem" over "not working at all" any day! 😄

**Comment by ruimarinho** [comment]
v4.0.0 has been released with Monterey support (which really just means playwright got a nice bump). Please let me know how your tests go and if we need to keep investigating the browser closing bug.

@akowalsk I was unable to replicate your issue. Please give v4.0.0 a try and let me know if it persists (preferably under a new ticket).
