### ISSUE TITLE
Display account aliases for roles

### ISSUE THREAD

**Issue by AlexeyRaga** [ruimarinho/gsts#55]
Hi! Currently `gsts` is capable of displaying roles that can be assumed for all the accounts.
Do you think it'd be possible to also get accounts' aliases so that it'd be easier to operate?

This feature exists in AWS SAML UI (`Production` and `Staging` on the screenshot), it'd be awesome to get it available with `gsts` too!

![image](https://user-images.githubusercontent.com/1394391/146458101-400b221e-6c69-4e73-8582-9a2ff8a15bc6.png)

**Comment by ruimarinho** [comment]
That looks good! Are you able to post the output of gsts in verbose mode so I can see its structure when aliases are included (redacting any sensitive information)?

**Comment by ruimarinho** [comment]
Closing since I haven't received any further feedback. Let me know if you're still interested in getting this added as I'm working on some changes right now.
