### ISSUE TITLE
Add Okta identity support

### ISSUE THREAD

**Issue by jorgetagle** [ruimarinho/gsts#59]
Hi @ruimarinho, my company is using Okta integrated with our Google services. This causes gsts to invalidate requests made to Okta resources and the authentication process gets stuck. As a quick workaround, I added the "okta" substring into the allowed identity resources and it worked well.

https://github.com/ruimarinho/gsts/blob/d3741f4a4a2d39983ed454b4e282191adbe35c5e/index.js#L313-L317

Do you think this would be the proper solution?

**Comment by dgacias** [comment]
Had the same issue, solved the same way as you:
$ sudo vim +313 /usr/local/lib/node_modules/gsts/index.js

Before:
if (/google|gstatic|youtube|googleusercontent|googleapis|gvt1/.test(route.request().url())) { 
Now:
 if (/google|gstatic|okta|youtube|googleusercontent|googleapis|gvt1/.test(route.request().url())) {

**Comment by ruimarinho** [comment]
Please give v4.1.0 a try and let me know if it's working as expected!
