### ISSUE TITLE
gsts clashes with ohmyzsh git plugin

### ISSUE THREAD

**Issue by trilom** [ruimarinho/gsts#7]
The plugin for git in ohmyzsh causes conflict with this.

https://github.com/ohmyzsh/ohmyzsh/tree/master/plugins/git

You can solve my either 1.) disabling the plugin or 2.) unaliasing at the end of your . files.

**Comment by trilom** [comment]
Other than this it worked perfectly.  Thank you for this!

**Comment by ruimarinho** [comment]
Ah, bummer! Thanks for note (added at https://github.com/ruimarinho/gsts/commit/746be58be8c1c23ccd4b74566ee1eab2a1438277). Used to be a big fan of ohmyzsh but decided to give zimfw a try until finally landing on zplugin most recently!

**Comment by saada** [comment]
Yeah ran into this as well.
For everyone else, add `unalias gsts` after loading the git plugin in your `~/.zshrc`.
