### ISSUE TITLE
Ubuntu jammy snap firefox errors on --clean

### ISSUE THREAD

**Issue by rwalerow** [ruimarinho/gsts#78]
Since moving to a new ubuntu installation(22 jammy) I do encounter an issue when running gsts with --clean option(It's needed from time to time)

Error looks like this: 
```
Please migrate your code to use AWS SDK for JavaScript (v3).
For more information, check the migration guide at https://a.co/7PzMCcy
(Use `node --trace-warnings ...` to show where the warning was created)
[Error: ENOENT: no such file or directory, mkdir '/var/snap/firefox/common/host-hunspell/.Trash-0'] {
  errno: -2,
  code: 'ENOENT',
  syscall: 'mkdir',
  path: '/var/snap/firefox/common/host-hunspell/.Trash-0'
}
```

I tried:
- changing engine with --engine flags -> seems to have no effect, error is always the same
- reinstalling gsts(I tried apt-get install as well as npm installation)
- reinstalling firefox -> jammy didn't accept firefox installation other then one provided via snap

Any suggestions?

**Comment by ruimarinho** [comment]
Thanks for the report @rwalerow. There was an issue with the `trash` package which appears to have been fixed by https://github.com/sindresorhus/trash/pull/124.

This will be addressed in https://github.com/ruimarinho/gsts/pull/81 which will land on the next major.
