### ISSUE TITLE
No credentials are written to ~/.aws/credentials as of v5.0.0

### ISSUE THREAD

**Issue by cvernooy23** [ruimarinho/gsts#91]
I have been using this for a while now, but as of upgrading to v5.0.0 the credentials are not written to ~/.aws/credentials. The last credentials I have in the file are from March 14, 2023, no matter how many times I run it nothing is written. 

output:

`✔ Login successful!`

I've double checked and confirmed my user is the owner of that file and has read write permissions. Are there any logs I can check? I have tried deleting all of the information in the file and deleting all but the profile "default" to no avail.

**Comment by amrutcatsalt** [comment]
By default credentials are read and writtien to Loaded credentials from "$HOME/Library/Caches/gsts/credentials" for profile "default".

Tried to set --cache-dir but did not help.
$ gsts --version                                                                                                                                                                                              
5.0.0

**Comment by reijmer** [comment]
I am experiencing the same issue on Mac

**Comment by jontg** [comment]
the 5.x line of gsts changed things significantly - see the notes in https://github.com/ruimarinho/gsts/pull/82 and specifically 
<img width="794" alt="image" src="https://github.com/ruimarinho/gsts/assets/309263/e8814560-9e5a-48ec-b0c8-4f3e72992d72">

The recommended path moving forward is 
<img width="479" alt="image" src="https://github.com/ruimarinho/gsts/assets/309263/07a5369b-abf0-41aa-bf5d-46cf8974adbb">

that is, *remove* the entry for your credentials from `~/.aws/credentials`, and *add*` a new line in `~/.aws/config` as per ☝️.

You may also find frustration working with multiple profiles.  Ping @ruimarinho and gently ask them to review/merge https://github.com/ruimarinho/gsts/pull/90 (or consider migrating to a fork that has this issue addressed).
