### ISSUE TITLE
brew install gsts@v4.0.1 failed

### ISSUE THREAD

**Issue by VinozzZ** [ruimarinho/gsts#92]
Hi team, I would like to install the older version through brew. However, it fails with bellow error
```
Error: No formulae or casks found for gsts@4.1.0.
```

I'm running the command: `brew install gsts@v4.0.1`

**Comment by ruimarinho** [comment]
Installed pinned versions via Homebrew is not supported. The v4 branch of gsts has been deprecated for a far more efficient and secure v5. Everything v4 did is done better by v5, so please share your concerns or issues if you're facing any. I'll try to address them!

If you really want to continue with v4, you can install via npm/yarn directly, as those versions remain published on the npm registry.
