### ISSUE TITLE
gsts v.5.0.0 stuck at Logging in

### ISSUE THREAD

**Issue by whhsu2** [ruimarinho/gsts#95]
gsts stuck at Logging in on a MacBook Pro
```sh
Now using node v18.14.2 (npm v9.5.0)
⠸ Logging in
```

It was all working a couple days ago, not sure how to debug. 
```sh
aws-cli/1.29.0 Python/3.11.4 Darwin/22.5.0 botocore/1.31.0
npm/9.5.0
```

**Comment by fireboy1919** [comment]
Getting the same issue.  I assume that google changed something.

**Comment by TrivediShilpesh** [comment]
Getting the same issue with all platfrom (windows, linux and macos)

**Comment by whhsu2** [comment]
Resolved! yall need to move the credentials from `~/.aws/credentials` to `/Users/{username}/Library/Caches/gsts/credentials`

**Comment by TrivediShilpesh** [comment]
still not working
